# Generated by Django 5.0.7 on 2024-12-29 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='公司名称')),
                ('website', models.URLField(blank=True, null=True, verbose_name='公司网站')),
                ('legal_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='法人')),
                ('status', models.CharField(choices=[('normal', '正常'), ('shared', '共享池')], default='normal', max_length=20, verbose_name='客户状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.employee', verbose_name='负责员工')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='联系人姓名')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人电话')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='联系人职位')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系人邮箱')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系人地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='customers.customer', verbose_name='客户')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
            },
        ),
    ]
